// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAWSProfiles() {
  return window['go']['app']['App']['GetAWSProfiles']();
}

export function GetAWSRegions() {
  return window['go']['app']['App']['GetAWSRegions']();
}

export function GetAllVPCs() {
  return window['go']['app']['App']['GetAllVPCs']();
}

export function SetAWSProfile(arg1) {
  return window['go']['app']['App']['SetAWSProfile'](arg1);
}

export function SetAWSRegion(arg1) {
  return window['go']['app']['App']['SetAWSRegion'](arg1);
}
