// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {awsdto} from '../models';

export function GetAWSProfiles():Promise<Array<awsdto.AWSProfileDTO>>;

export function GetAWSRegions():Promise<Array<string>>;

export function GetAllVPCs():Promise<Array<awsdto.VPCDTO>>;

export function SetAWSProfile(arg1:string):Promise<void>;

export function SetAWSRegion(arg1:string):Promise<void>;
